name: Badua

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Copy ba-dua-agent-rt
        run: mvn dependency:copy -Dartifact=br.usp.each.saeg:ba-dua-agent-rt-0.6.0-all -DoutputDirectory=./ba-dua

      - name: Copy ba-dua-cli
        run: mvn dependency:copy -Dartifact=br.usp.each.saeg:ba-dua-cli-0.8.0-all -DoutputDirectory=./ba-dua

      - name: Badua check
        run: mvn -B clean verify -P badua -Drat.skip=true

      - name: Add Badua report
        uses: actions/upload-artifact@v3
        with:
          name: badua-report
          path: openjpa-kernel/target/badua.xml